[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skydock2"
version = "0.1.0"
description = "Skydock drone control with AI"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "opencv-python",
]

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["venv*", "*.egg-info"]
